# Generated by Django 4.0.4 on 2022-06-02 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_like_liked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='timestamp',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='timestamp',
            new_name='date',
        ),
    ]
