# Generated by Django 4.0.4 on 2022-06-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_timestamp_like_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='request',
            field=models.CharField(default="GET 'None'", max_length=200),
        ),
    ]
